### PR TITLE
Build a Dialyzer PLT when installing a build

### PR DESCRIPTION
**Pull request by erszcz**
It's convenient to have a global PLT with all Erlang/OTP apps to reuse in multiple projects and cut down on time needed to build a per-project PLT.
This PR makes it possible to define a `KERL_BUILD_PLT` (on the command line or in `.kerlrc`) variable, which if set will make `kerl` build a PLT of all apps going into an installation. `kerl plt` will print availability of a PLT for the active installation. Such a modification was also made to `kerl status`.
Tested with 17.1 and 18.0 - no problems encountered.

This is based on top of #100 issued separately.

### CODE REVIEW

**Comment by tomekowal** [comment]
:+1:

**Comment by mrallen1** [comment]
Really like this idea. :+1: What do you think @sanmiguel?

**Comment by sanmiguel** [comment]
Agreed @mrallen1 - this seems like something that would be very useful. :+1:

**Comment by mrallen1** [comment]
I think we want to refactor how documentation get built even further, but this is a nice 1st step.

**Pull request merged**
